const ACTION_TYPES = {
  'SIGN_IN': 'SIGN_IN',
  'SIGN_IN_SUCCESS': 'SIGN_IN_SUCCESS',
  'SIGN_IN_ERROR': 'SIGN_IN_ERROR',
  'GET_ARTICLE_DETAIL': 'GET_ARTICLE_DETAIL',
  'GET_ARTICLE_DETAIL_SUCCESS': 'GET_ARTICLE_DETAIL_SUCCESS'
};

export default ACTION_TYPES;
